name: Scheduled Merge Remote Action
on: 
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 

    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch upstream
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git fetch upstream
        git checkout main        
        git merge upstream/main

        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push origin main
